package com.newhope.moneyfeed.feedback.api.bean;

import com.newhope.moneyfeed.api.bean.BaseModel;
import java.util.Date;

public class CsAttachmentsModel extends BaseModel {
    private Long id;

    private Long masterId;

    private String realFileName;

    private String fileName;

    private String fileType;

    private Long fileSize;

    private String saveAddress;

    private String uri;

    private Date uploaded;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_attachments.id
     *
     * @return the value of cs_attachments.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_attachments.id
     *
     * @param id the value for cs_attachments.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_attachments.master_id
     *
     * @return the value of cs_attachments.master_id
     *
     * @mbggenerated
     */
    public Long getMasterId() {
        return masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_attachments.master_id
     *
     * @param masterId the value for cs_attachments.master_id
     *
     * @mbggenerated
     */
    public void setMasterId(Long masterId) {
        this.masterId = masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_attachments.real_file_name
     *
     * @return the value of cs_attachments.real_file_name
     *
     * @mbggenerated
     */
    public String getRealFileName() {
        return realFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_attachments.real_file_name
     *
     * @param realFileName the value for cs_attachments.real_file_name
     *
     * @mbggenerated
     */
    public void setRealFileName(String realFileName) {
        this.realFileName = realFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_attachments.file_name
     *
     * @return the value of cs_attachments.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_attachments.file_name
     *
     * @param fileName the value for cs_attachments.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_attachments.file_type
     *
     * @return the value of cs_attachments.file_type
     *
     * @mbggenerated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_attachments.file_type
     *
     * @param fileType the value for cs_attachments.file_type
     *
     * @mbggenerated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_attachments.file_size
     *
     * @return the value of cs_attachments.file_size
     *
     * @mbggenerated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_attachments.file_size
     *
     * @param fileSize the value for cs_attachments.file_size
     *
     * @mbggenerated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_attachments.save_address
     *
     * @return the value of cs_attachments.save_address
     *
     * @mbggenerated
     */
    public String getSaveAddress() {
        return saveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_attachments.save_address
     *
     * @param saveAddress the value for cs_attachments.save_address
     *
     * @mbggenerated
     */
    public void setSaveAddress(String saveAddress) {
        this.saveAddress = saveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_attachments.uri
     *
     * @return the value of cs_attachments.uri
     *
     * @mbggenerated
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_attachments.uri
     *
     * @param uri the value for cs_attachments.uri
     *
     * @mbggenerated
     */
    public void setUri(String uri) {
        this.uri = uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_attachments.uploaded
     *
     * @return the value of cs_attachments.uploaded
     *
     * @mbggenerated
     */
    public Date getUploaded() {
        return uploaded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_attachments.uploaded
     *
     * @param uploaded the value for cs_attachments.uploaded
     *
     * @mbggenerated
     */
    public void setUploaded(Date uploaded) {
        this.uploaded = uploaded;
    }
}